Feat/avm best practices
Azure/terraform-azurerm-avm-ptn-aks-production pull request #41
Opened 2024-04-10 09:31 UTC by nellyk

## Description

## Type of Change

- [ ] Non-module change (e.g. CI/CD, documentation, etc.)
- [ ] Azure Verified Module updates:
  - [ ] Bugfix containing backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `locals.version.tf.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `locals.version.tf.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `locals.version.tf.json`.
  - [ ] Update to documentation

# Checklist

- [ ] I'm sure there are no other open Pull Requests for the same update/change
- [ ] My corresponding pipelines / checks run clean and green without any errors or warnings
- [ ] I did run all  [pre-commit](https://azure.github.io/Azure-Verified-Modules/contributing/terraform/terraform-contribution-flow/#5-run-pre-commit-checks) checks

2024-04-10 12:02 UTC, nellyk commented on .terraform-docs.yml
> +  lockfile: true
updated as per https://azure.github.io/Azure-Verified-Modules/specs/terraform/#id-tfnfr2---category-documentation---module-documentation-generation

2024-04-10 12:15 UTC, nellyk commented on main.tf
> +  name                = "cr${random_string.acr_suffix.result}"
based on this https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations

2024-04-10 12:15 UTC, nellyk commented on outputs.tf
> +
using this for the unit tests

2024-04-10 12:15 UTC, nellyk reviewed
ok

2024-04-12 13:14 UTC, zioproto requested changes

2024-04-12 13:14 UTC, zioproto commented on main.tf
> +
why the empty lines ?

2024-04-12 13:14 UTC, zioproto commented on README.md
> +<!-- END_TF_DOCS -->
is this generated, right ? How is possible that the automation added the trailing whitespaces ?

2024-04-12 13:14 UTC, zioproto commented on terraform.tf
> +
why the empty lines ?

2024-04-12 16:40 UTC, nellyk commented on .terraform-docs.yml
can't use `coalescelist ` because it fails with following error. Even when the value is provided 
│ Error: Null value found in list
│ 
│   with module.test.module.vnet.azurerm_virtual_network.vnet,
│   on .terraform/modules/test.vnet/main.tf line 2, in resource "azurerm_virtual_network" "vnet":
│    2:   address_space           = var.virtual_network_address_space
│ 
│ Null values are not allowed for this attribute value.

2024-04-15 09:53 UTC, zioproto approved these changes

2024-04-15 09:53 UTC, merged